---
- name: Install NFS packages
  apt:
    name:
      - nfs-kernel-server
      - rpcbind
    state: present
    update_cache: true

- name: Ensure nfs-server is enabled and running
  systemd:
    name: nfs-server
    enabled: yes
    state: started

- name: Ensure rpcbind is enabled and running
  systemd:
    name: rpcbind
    enabled: yes
    state: started

- name: Add NFS export to /etc/exports
  lineinfile:
    path: /etc/exports
    line: "/home/edward/apps\t10.8.8.124(rw,sync,no_root_squash,no_subtree_check)"
    state: present

- name: Apply NFS export configuration
  command: exportfs -ra
  no_log: true

- name: Restart NFS services
  systemd:
    name: nfs-server
    state: restarted
