---
- name: Render and Apply Cert-Manager Configurations
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  block:
    - name: Render Issuer Secret
      ansible.builtin.template:
        src: clusterissuer-secret.yaml.j2
        dest: /tmp/clusterissuer-secret.yaml
        mode: "0600"

    - name: Render Production Issuer
      ansible.builtin.template:
        src: clusterissuer-cloudflare.yaml.j2
        dest: /tmp/clusterissuer-cloudflare.yaml
        mode: "0600"

    - name: Apply Kubernetes Configurations
      kubernetes.core.k8s:
        src: "{{ item }}"
        state: present
        kubeconfig: /etc/rancher/rke2/rke2.yaml
      loop:
        - /tmp/clusterissuer-secret.yaml
        - /tmp/clusterissuer-cloudflare.yaml
