all:
  children:
    rke2_cluster:
      children:
        rke2_servers:
          hosts:
            server-01:
              ansible_host: 10.8.8.160
            server-02:
              ansible_host: 10.8.8.161
            server-03:
              ansible_host: 10.8.8.162
        rke2_agents:
          hosts:
            agent-01:
              ansible_host: 10.8.8.163
            agent-02:
              ansible_host: 10.8.8.164
    ubuntu_server_setup:
      hosts:
        new-vm:
          ansible_host: 10.8.8.121
