all:
  children:
    rke2_cluster:
      children:
        rke2_servers:
          hosts:
            rke-node-01:
              ansible_host: 10.8.8.160
            rke-node-02:
              ansible_host: 10.8.8.161
            rke-node-03:
              ansible_host: 10.8.8.162
        rke2_agents:
          hosts:
            rke-node-04:
              ansible_host: 10.8.8.163
            rke-node-05:
              ansible_host: 10.8.8.164
    ubuntu_server_setup:
      hosts:
        new-vm:
          ansible_host: 10.8.8.121
