---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBZBIYk2VeuWk23QGcQWkMYw6aJhAL3e1zO7jiySqHJ2okVMWNVmB1QNoBxnWP870zu8jYR4ywYZX/bxr625j5L0xzou4SHwMwop0UGmhZoG0rH0SYdtKJcpR63FU/gQB/BTFhoLzWqCTP08QwhQIrko3yj0YS5GbTwYNHbCqp5R09Zy7LYg1E/VZ6TpihuIfZxmSyqhpnwewCEvuusSJ+NL1z9kX7Ifi1m2Jw2IPxzBc4bRVZj2Dkfha0Pm4kGt55EXf02NailgwhmQVlHGJ60jNu4DYLyk2vyLDGVQD138rK0GrwO3wsluHMlvkdLH4x3/EA3pgFhsmwV1pnLHDqn/unu4YzpCwqwAkowvKCC8RW03zHzb7gzlWtu0T1fBdNh+uo0Is+1jh+CWPxwgjTqpHwP7/OdmjuwqOVYGzcPeX6hpQlBmtvQ6vbcwRbpkCUgV8s5iUnR2DNy2NxTJ1Ryys8UjTjkevEn21okuITHSrKq6KjDVsI8+a096ZCBr4tUS5ktzaRCJiJeG3SQ+F1TPm48eB33DMcQYiLI+B5GE3O9bnVyA1oV4vPa77Bjf6sC/br/SPyaU4pkoVekrvRxVMzqiwpRyImzD025dXjlcstwRd8TmJ/h6yAinDrk5xq+IYdGkGg9x94VETY+semHOiQ/uDoC7b5zOFrK/G4u52u1JYBRH12nV4wk5gRiW+HCvpj67Mwsr1HBJCbCAjKnlpewZfRxue8tQpgqK6ixyZVmmyXP4qTN
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
