---
- name: Prepare agent nodes
  hosts: rke2_agents
  become: true
  roles:
    - traefik/configure-labels

- name: Deploy Traefik to agent nodes
  hosts: rke2_servers
  become: true
  roles:
    - traefik/deploy
