---
- name: Deploy and configure Longhorn
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  block:
    - name: Create Longhorn namespace
      kubernetes.core.k8s:
        name: "{{ longhorn_config.namespace }}"
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: "{{ longhorn_kubernetes_config.path }}"
      tags:
        - longhorn
        - namespace

    - name: Template Longhorn values
      ansible.builtin.template:
        src: templates/longhorn-values.yaml.j2
        dest: /tmp/longhorn-values.yaml
        mode: "0644"
      tags:
        - longhorn
        - deploy

    - name: Deploy Longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: "{{ longhorn_config.namespace }}"
        create_namespace: true
        wait: true
        wait_timeout: "{{ longhorn_config.wait_timeout }}"
        values_files:
          - /tmp/longhorn-values.yaml
        kubeconfig: "{{ longhorn_kubernetes_config.path }}"
      tags:
        - longhorn
        - deploy
