---
galaxy_info:
  author: Edward Kerckhof
  description: Configures cert-manager ClusterIssuer
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - kubernetes
    - certificates

dependencies:
  - role: deploy
