---
- name: Restart RKE2 server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted
    daemon_reload: true

- name: Restart RKE2 agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted
    daemon_reload: true

- name: Clean temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/rke2-config.yaml
    - /tmp/node-token
