---
- name: Copy kubectl to user bin
  ansible.builtin.copy:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    mode: "0755"
    remote_src: true
  become: true
  when: inventory_hostname == groups['rke2_servers'][0]

- name: Wait for kubectl
  ansible.builtin.wait_for:
    path: /usr/local/bin/kubectl
  when: inventory_hostname == groups['rke2_servers'][0]

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="
  when: inventory_hostname == groups['rke2_servers'][0]
  notify: Clean temporary files

- name: Replace IP address with server1
  ansible.builtin.replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: "127.0.0.1"
    replace: "{{ hostvars['server-01']['ansible_host'] }}"
  when: inventory_hostname == groups['rke2_servers'][0]
