---
- name: Run preflight checks
  ansible.builtin.import_tasks: preflight.yaml
  tags: ["rke2", "preflight"]

- name: Setup directories
  ansible.builtin.import_tasks: directories.yaml
  tags: ["rke2", "directories"]

- name: Configure RKE2 services
  ansible.builtin.import_tasks: services.yaml
  tags: ["rke2", "services"]

- name: Handle master node setup
  ansible.builtin.import_tasks: master_node.yaml
  when: inventory_hostname == groups['rke2_servers'][0]
  tags: ["rke2", "server"]

- name: Configure kubectl
  ansible.builtin.import_tasks: kubectl.yaml
  tags: ["rke2", "kubectl"]

- name: Handle token configuration
  ansible.builtin.import_tasks: token.yaml
  tags: ["rke2", "token"]
