---
- name: Deploy RKE2 server Configuration
  ansible.builtin.template:
    src: templates/rke2-server-config.j2
    dest: "{{ rke2_config.config.dir }}/config.yaml"
    owner: root
    group: root
    mode: "{{ rke2_config.config.mode }}"
  when: inventory_hostname in groups['rke2_servers']

- name: Create systemd service file for RKE2 server
  ansible.builtin.template:
    src: templates/rke2-server.service.j2
    dest: "/etc/systemd/system/{{ rke2_config.server.service_name }}.service"
    owner: root
    group: root
    mode: "{{ rke2_file_permissions.default_mode }}"
  when: inventory_hostname in groups['rke2_servers']

- name: Create systemd service file for RKE2 agent
  ansible.builtin.template:
    src: templates/rke2-agent.service.j2
    dest: "/etc/systemd/system/{{ rke2_config.agent.service_name }}.service"
    owner: root
    group: root
    mode: "{{ rke2_file_permissions.default_mode }}"
  when: inventory_hostname in groups['rke2_agents']

- name: Trigger RKE2 server restart for other servers
  ansible.builtin.debug:
    msg: "Triggering RKE2 server restart"
  when: inventory_hostname in groups['rke2_servers'][1:]
  notify: Restart RKE2 server

- name: Trigger RKE2 agent restart
  ansible.builtin.debug:
    msg: "Triggering RKE2 agent restart"
  when: inventory_hostname in groups['rke2_agents']
  notify: Restart RKE2 agent
