---
- name: Ensure the timezone is set
  timezone:
    name: "{{ timezone }}"

- name: Install qemu-guest-agent
  apt:
    name:
      - qemu-guest-agent
    state: present
    update_cache: true

- name: Ensure qemu-guest-agent is enabled and running
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started

- name: Install iptables
  apt:
    name:
      - iptables
    state: present
    update_cache: true

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true
  tags: sysctl

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  tags: sysctl
