---
- name: Deploy Traefik
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  block:
    - name: Template Traefik values
      ansible.builtin.template:
        src: templates/traefik-values.yaml.j2
        dest: /tmp/traefik-values.yaml
        mode: '0644'
      notify: cleanup temporary files

    - name: Deploy Traefik
      kubernetes.core.helm:
        name: traefik
        chart_ref: "{{ traefik_config.helm.chart_name }}"
        release_namespace: "{{ traefik_config.namespace }}"
        create_namespace: true
        wait: true
        wait_timeout: "{{ traefik_config.wait_timeout }}"
        kubeconfig: "{{ traefik_kubernetes_config.path }}"
        values_files:
          - /tmp/traefik-values.yaml
