---
- name: Install and configure Helm
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  block:
    - name: Install Helm
      ansible.builtin.get_url:
        url: "{{ traefik_helm_config.install_script_url }}"
        dest: /tmp/get-helm.sh
        mode: '0700'
      notify: cleanup temporary files

    - name: Execute Helm installer
      ansible.builtin.command:
        cmd: /tmp/get-helm.sh
        creates: "{{ helm.binary_path }}"

    - name: Add Traefik Helm repository
      kubernetes.core.helm_repository:
        name: "{{ traefik.helm.repo_name }}"
        repo_url: "{{ traefik.helm.repo_url }}"
