---
- name: Check if Traefik namespace exists
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  ansible.builtin.command:
    cmd: kubectl get namespace traefik --kubeconfig /etc/rancher/rke2/rke2.yaml
  register: namespace_check
  failed_when: namespace_check.rc != 0 and 'Error from server (NotFound)' not in namespace_check.stderr
  changed_when: false

- name: Install Helm
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  block:
    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: "0700"

    - name: Execute Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
  when: namespace_check.rc != 0

- name: Add Traefik Helm repository
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts
  when: namespace_check.rc != 0

- name: Template custom values file
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  template:
    src: values.yaml.j2
    dest: /tmp/traefik-values.yaml
  when: namespace_check.rc != 0

- name: Deploy Traefik via Helm
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: traefik
    create_namespace: true
    state: present
    atomic: true
    kubeconfig: /etc/rancher/rke2/rke2.yaml
    values_files: ["/tmp/traefik-values.yaml"]
    values:
      service:
        type: LoadBalancer
  when: namespace_check.rc != 0

- name: Render Middleware YAML file
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  template:
    src: default-headers-middleware.yaml.j2
    dest: /tmp/middleware.yaml
  when: namespace_check.rc != 0

- name: Apply Middleware using kubectl
  delegate_to: "{{ groups['rke2_servers'][0] }}"
  run_once: true
  command: kubectl apply -f /tmp/middleware.yaml --kubeconfig /etc/rancher/rke2/rke2.yaml
  when: namespace_check.rc != 0
