---
- name: Run preflight checks
  ansible.builtin.import_tasks: preflight.yml
  tags: ["traefik", "preflight"]

- name: Setup Helm
  ansible.builtin.import_tasks: helm.yml
  tags: ["traefik", "helm"]

- name: Deploy Traefik
  ansible.builtin.import_tasks: deploy.yml
  tags: ["traefik", "deploy"]

- name: Configure middleware
  ansible.builtin.import_tasks: middleware.yml
  tags: ["traefik", "middleware"]
