---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  issuerRef:
    name: cloudflare-clusterissuer
    kind: ClusterIssuer
  dnsNames:
    - longhorn-dashboard.zonedev.be
