---
- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_url }}"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present
    update_cache: yes

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Ensure Edward is in sudo and docker groups
  user:
    name: edward
    groups: "sudo,docker"
    append: yes
    state: present

- name: Ensure Docker service is enabled and running
  systemd:
    name: docker
    enabled: true
    state: started
