---
# We add "agent=true" to our agent configs so that when we deploy Traefik,
# It will be deployed on our agent nodes (workers) and not our servers (masters)
- name: Configure Agent node labels
  block:
    - name: Ensure RKE2 agent config directory exists
      file:
        path: /etc/rancher/rke2
        state: directory

    - name: Ensure the "node-label" key exists
      lineinfile:
        path: /etc/rancher/rke2/config.yaml
        regexp: "^node-label:"
        line: "node-label:"
        state: present

    - name: Add "agent=true" to node-label
      lineinfile:
        path: /etc/rancher/rke2/config.yaml
        regexp: '^\s*- "agent=true"$'
        line: '  - "agent=true"'
        state: present
        insertafter: "^node-label:"
      notify: restart rke2-agent
